-- Classic text smileys; artwork credits in assets/emotes/SOURCES.txt.
local _, addon = ...
addon.Emotes = {
    [":||"] = "neutral", -- Chat transport escapes literal pipes.
    [":-||"] = "neutral",
    ["%)"] = "silly",
    ["%-)"] = "silly",
    ["8)"] = "glasses-cool",
    ["8-)"] = "glasses-cool",
    [":'("] = "crying",
    [":'-("] = "crying",
    [":("] = "sad",
    [":)"] = "happy",
    [":*"] = "kiss",
    [":-("] = "sad",
    [":-)"] = "happy",
    [":-*"] = "kiss",
    [":-/"] = "thinking",
    [":-@"] = "shout",
    [":-D"] = "excited",
    [":-O"] = "shocked",
    [":-P"] = "tongue",
    [":-S"] = "confused",
    [":-X"] = "shut-mouth",
    [":-["] = "embarrassed",
    [":-\\"] = "thinking",
    [":-d"] = "excited",
    [":-o"] = "shocked",
    [":-p"] = "tongue",
    [":-s"] = "confused",
    [":-x"] = "shut-mouth",
    [":-|"] = "neutral",
    [":/"] = "thinking",
    [":0"] = "shocked",
    [":@"] = "shout",
    [":D"] = "excited",
    [":O"] = "shocked",
    [":P"] = "tongue",
    [":S"] = "confused",
    [":X"] = "shut-mouth",
    [":["] = "embarrassed",
    [":\\"] = "thinking",
    [":d"] = "excited",
    [":o"] = "shocked",
    [":p"] = "tongue",
    [":s"] = "confused",
    [":x"] = "shut-mouth",
    [":|"] = "neutral",
    [";'("] = "crying",
    [";)"] = "wink",
    [";-)"] = "wink",
    [";-D"] = "wink",
    [";D"] = "wink",
    [";P"] = "tongue",
    [";_;"] = "crying",
    [";p"] = "tongue",
    ["</3"] = "love-over",
    ["<3"] = "in_love",
    ["<\\3"] = "love-over",
    ["=("] = "sad",
    ["=)"] = "happy",
    ["=*"] = "kiss",
    ["=-O"] = "shocked",
    ["=-o"] = "shocked",
    ["=/"] = "thinking",
    ["=D"] = "excited",
    ["=P"] = "tongue",
    ["=\\"] = "thinking",
    ["=d"] = "excited",
    ["=p"] = "tongue",
    ["=|"] = "neutral",
    [">:("] = "angry",
    [">:)"] = "devil",
    [">:-("] = "angry",
    [">:-)"] = "devil",
    [">:O"] = "shout",
    [">:o"] = "shout",
    ["B)"] = "glasses-cool",
    ["B-)"] = "glasses-cool",
    ["O.o"] = "confused",
    ["O:)"] = "angel",
    ["O:-)"] = "angel",
    ["O_o"] = "confused",
    ["T.T"] = "crying",
    ["T_T"] = "crying",
    ["X("] = "angry",
    ["X-("] = "angry",
    ["X-D"] = "laugh",
    ["XD"] = "laugh",
    ["Xd"] = "laugh",
    ["]:->"] = "devil",
    ["^^"] = "happy",
    ["^_^"] = "happy",
    ["o.O"] = "confused",
    ["o:)"] = "angel",
    ["o:-)"] = "angel",
    ["o_O"] = "confused",
    ["x-("] = "angry",
    ["x-D"] = "laugh",
    ["xD"] = "laugh",
    ["xd"] = "laugh",
}

addon.EmotePicker = {
    { text = ":)", asset = "happy" },
    { text = ":D", asset = "excited" },
    { text = ";)", asset = "wink" },
    { text = ":P", asset = "tongue" },
    { text = ":(", asset = "sad" },
    { text = ":'(", asset = "crying" },
    { text = "XD", asset = "laugh" },
    { text = ":O", asset = "shocked" },
    { text = ":/", asset = "thinking" },
    { text = ":|", asset = "neutral" },
    { text = ":*", asset = "kiss" },
    { text = "B)", asset = "glasses-cool" },
    { text = ">:(", asset = "angry" },
    { text = ">:O", asset = "shout" },
    { text = ":S", asset = "confused" },
    { text = ":[", asset = "embarrassed" },
    { text = ":X", asset = "shut-mouth" },
    { text = "O:)", asset = "angel" },
    { text = ">:)", asset = "devil" },
    { text = "%)", asset = "silly" },
    { text = "<3", asset = "in_love" },
    { text = "</3", asset = "love-over" },
}
