-- Lua 5.1 is the shared language baseline for supported WoW clients.
std = "lua51"
exclude_files = { "scripts/libraries/**" }
codes = true
-- StyLua owns line wrapping, including strings that cannot be split safely.
max_line_length = false
-- WoW callbacks and colon methods intentionally leave some parameters unused.
unused_args = false

globals = { "Chatter", "StaticPopupDialogs" }
-- Explicit WoW/Ace globals: unknown names and accidental globals still fail lint.
read_globals = {
    "ACCEPT",
    "AddFriend",
    "AddIgnore",
    "BNGetNumFriends",
    "BNInviteFriend",
    "BNSendGameData",
    "BNSendWhisper",
    "BNSetBlocked",
    "BNet_GetBNetIDAccount",
    "CANCEL",
    "CHAT_FRAMES",
    "CLASS_ICON_TCOORDS",
    "C_AddOns",
    "C_BattleNet",
    "C_ChatInfo",
    "C_FriendList",
    "C_PartyInfo",
    "C_Timer",
    "ChatEdit_ActivateChat",
    "ChatEdit_DeactivateChat",
    "ChatEdit_GetActiveWindow",
    "ChatEdit_InsertLink",
    "ChatEdit_UpdateHeader",
    "ChatFrameUtil",
    "ChatFrame_AddMessageEventFilter",
    "ChatFrame_ReplyTell",
    "ChatFrame_ReplyTell2",
    "ChatFrame_SendBNetTell",
    "ChatFrame_SendTell",
    "CreateFrame",
    "DelIgnore",
    "Enum",
    "GameFontHighlight",
    "GameTooltip",
    "GetAddOnMetadata",
    "GetBuildInfo",
    "GetCursorPosition",
    "GetFriendInfo",
    "GetGuildInfo",
    "GetGuildRosterInfo",
    "GetMouseFoci",
    "GetMouseFocus",
    "GetNormalizedRealmName",
    "GetNumFriends",
    "GetNumGroupMembers",
    "GetNumGuildMembers",
    "GetPlayerInfoByGUID",
    "GetTime",
    "HasAnySecretValues",
    "HideUIPanel",
    "InCombatLockdown",
    "InterfaceOptionsFrame",
    "InviteUnit",
    "IsInGroup",
    "IsInRaid",
    "IsMouseButtonDown",
    "LOCALIZED_CLASS_NAMES_FEMALE",
    "LOCALIZED_CLASS_NAMES_MALE",
    "LibStub",
    "LoadAddOn",
    "MenuUtil",
    "PLAYER_OFFLINE",
    "PlaySoundFile",
    "RAID_CLASS_COLORS",
    "RegisterAddonMessagePrefix",
    "ReportFrame",
    "ReportInfo",
    "SendAddonMessage",
    "SendChatMessage",
    "SetItemRef",
    "SettingsPanel",
    "StaticPopup_Show",
    "UIParent",
    "UNKNOWN",
    "UNKNOWNOBJECT",
    "UnitClass",
    "UnitExists",
    "UnitFullName",
    "UnitGUID",
    "UnitInParty",
    "UnitInRaid",
    "UnitIsConnected",
    "UnitIsGroupAssistant",
    "UnitIsGroupLeader",
    "UnitIsPlayer",
    "UnitLevel",
    "UnitName",
    "UnitNameUnmodified",
    "UnitPopupSharedUtil",
    "UnitRace",
    "WOW_PROJECT_ID",
    "date",
    "hooksecurefunc",
    "strtrim",
    "time",
}

-- Harnesses provide mutable WoW globals and frame mocks outside the game.
files["tests/**"] = {
    globals = read_globals,
    allow_defined = true,
    -- Mock globals are consumed by loadfile() modules. Independent test cases
    -- also reuse local names and define nested frame methods with their own self.
    ignore = { "131", "4" },
}

files["tests/settings.lua"] = {
    globals = { "table.wipe" },
}
